# Generated by Django 5.1.3 on 2025-09-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_token_access_token_alter_token_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
