# Generated by Django 5.1.3 on 2025-09-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_token_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gmail_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
