# Generated by Django 5.1.3 on 2025-09-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_gmail_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linked_in_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
