# Generated by Django 5.1.3 on 2025-09-23 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_facebooktoken_token_facebook_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='facebook_page',
        ),
        migrations.AddField(
            model_name='facebooktoken',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facebook_tokens', to='authentication.token'),
        ),
    ]
