# Generated by Django 5.1.3 on 2025-09-23 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_token_facebook_page_facebooktoken_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facebooktoken',
            old_name='page_id',
            new_name='account_id',
        ),
    ]
