# Generated by Django 5.1.3 on 2025-09-23 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_rename_page_id_facebooktoken_account_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facebooktoken',
            old_name='page_access_token',
            new_name='access_token',
        ),
    ]
