# Generated by Django 5.1.3 on 2025-09-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_rename_page_access_token_facebooktoken_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whatsapp_phone_number_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
