# Generated by Django 5.1.3 on 2025-09-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_user_whatsapp_phone_number_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='instagram_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
