# Generated by Django 5.1.3 on 2025-09-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_token_instagram_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='instagram_access_token',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
