# Generated by Django 5.1.3 on 2025-09-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_token_instagram_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=100),
        ),
    ]
