# Generated by Django 5.1.3 on 2025-09-25 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_instagramtoken'),
    ]
    operations = [
        migrations.RemoveField(
            model_name="instagramtoken",
            name="facebook_token",
        ),
        migrations.AddField(
            model_name="instagramtoken",
            name="facebook_token",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instagram_tokens', to='authentication.facebooktoken'),
        ),
    ]


    