# Generated by Django 5.1.3 on 2025-09-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0005_department_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='channel',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('gmail', 'Gmail'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('general', 'General'), ('instagram', 'Instagram')], default='general', max_length=50),
        ),
    ]
