[pytest]
DJANGO_SETTINGS_MODULE = api.settings
pythonpath = .
addopts = 
    --ds=api.settings
    --cov=api/instagram
    --cov-report=term-missing
    --cov-report=html
    --cov-config=.coveragerc
norecursedirs =
    .git
    .tox
    .env
    venv
    node_modules
    staticfiles
    api/instagram/migrations
    api/helpers
    api/analyst
    api/templates
    api/prompt
    api/scout
testpaths =
    api/instagram/tests

