# Generated by Django 5.1.3 on 2025-09-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_endpoint_results_alter_workflowmodel_workflow_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='url_kwargs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], default='GET', max_length=10),
        ),
    ]
