# Generated by Django 5.1.3 on 2025-09-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_endpoint_url_kwargs_alter_endpoint_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='airflowcreds',
            name='airflow_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
