# Generated by Django 5.1.3 on 2025-09-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_remove_dagmodel_dag_run_id_remove_dagmodel_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowmodel',
            name='provider',
            field=models.CharField(blank=True, choices=[('facebook', 'facebook'), ('instagram', 'instagram'), ('linkedin', 'linkedin'), ('whatsapp', 'whatsapp'), ('google', 'google')], max_length=255, null=True),
        ),
    ]
