# Generated by Django 5.1.3 on 2025-09-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_workflowmodel_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='extra_params',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
