# Generated by Django 5.1.3 on 2025-09-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_endpoint_extra_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplehttpoperatormodel',
            name='token',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
