# Generated by Django 5.1.3 on 2025-09-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebookautomator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='stop',
            field=models.BooleanField(default=False),
        ),
    ]
