# Generated by Django 5.1.3 on 2025-09-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('conversation_history', models.JSONField(default=list)),
                ('stop', models.BooleanField(default=False)),
            ],
        ),
    ]
