# -*- coding: utf-8 -*-
"""Copy of lunyamwi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14G0swwAY24Z2hksaUtZSQ8xwM9PXyLpD

# Data Structures and Algorithms
"""

print( "Welcome to the GPA calculator." )
print( "Please enter all your letter grades, one per line." )
print( "Enter a blank line to designate the end." )
# map from letter grade to point value
points = { "A+" :4.0, "A" :4.0, "A-" :3.67, "B+" :3.33, "B" :3.0, "B-" :2.67,
"C+" :2.33, "C" :2.0, "C" :1.67, "D+" :1.33, "D" :1.0, "F" :0.0}
num_courses = 0
total_points = 0
done = False
while not done:
  grade = input()
  if grade == "":
    done = True
  elif grade not in points:
    print(f"Unknown grade {grade} being ignored")
  else:
    num_courses += 1
    total_points += points[grade]
if num_courses > 0:
    print(f"Your GPA is {total_points / num_courses}")

temperature = 98.6

temperature = None




temperature = 98.6

original = temperature

temperature = temperature + 5.0

temperature,original

help(float)

bool()

bool(23==24)

bool(24>23)

int()

int('334')

float()

largest = 6.022 * (10 ** 23)

type(largest)

float(4)

float('3.14159')

str_one = "hello"

str_one.upper()

str_one.capitalize()

str_one[1]

str_two = 'Don\'t worry about apostrophes \n It is very interesting \n this is just amazing'
print(str_two.rjust(0))

list_one = list(str_one)

list_one[1] = 'a'

list_one

list_two = [1,2,3,4,5]

type(list_two)

tuple_one = tuple(str_one)

# tuple_one[1] = 'a'

set_one = set(str_one)
set_one

frozenset_one = frozenset(str_one)
frozenset_one

dict_one = {'A+': 4.0,
 'A': 4.0,
 'A-': 3.67,
 'B+': 3.33,
 'B': 3.0,
 'B-': 2.67,
 'C+': 2.33,
 'C': 1.67,
 'D+': 1.33,
 'D': 1.0,
 'F': 0.0}
dict(dict_one)

#not,and,or
(23 != 24 & 24 == 24) | (23 == 22)

23 != 24 and 24 == 24 or 23 == 22

#is (==), is not (!=)
23 is not 24 and 24 is 24 or 23 is 22

# <,<=,>,>=
23 <= 24 and 24 >= 24 or 23 < 22

# 5 < 'hello'

# +, -, *, /, //, %

(23 + 24) % 2

# ~,&, |, ^, <<, >>

#, in, not in

list_three = [1,2,5,6,7,8,9,10]
bool(3 in list_three)
bool(3 not in list_three)
bool(5 in list_three)

temperature = 89.7

temperature += 5

temperature

if 1 not in list_three:
  print("yeah 1 is not in list 3")
elif 3 not in list_three:
  print("oh no 3 is in list 3")
else:
  print("oh no failures")

int_one  = 23

for i in str_one:
  print(i)

len(str_one)

j = 0
while j < len(str_one):
  j+= 1

j

# my own len
def counter(data, target):
  n = 0
  for item in data:
    if item == target:
      n += 1
  return n

counter(str_one,'e')

"""## Assignment"""

# R-1.1 Write a short Python function, is multiple(n, m), that takes two integer
# values and returns True if n is a multiple of m, that is, n = mi for some
# integer i, and False otherwise.
# R-1.2 Write a short Python function, is even(k), that takes an integer value and
# returns True if k is even, and False otherwise. However, your function
# cannot use the multiplication, modulo, or division operators.
# R-1.3 Write a short Python function, minmax(data), that takes a sequence of
# one or more numbers, and returns the smallest and largest numbers, in the
# form of a tuple of length two. Do not use the built-in functions min or
# max in implementing your solution.
# R-1.4 Write a short Python function that takes a positive integer n and returns
# the sum of the squares of all the positive integers smaller than n.
# R-1.5 Give a single command that computes the sum from Exercise R-1.4, rely-
# ing on Python’s comprehension syntax and the built-in sum function.
# R-1.6 Write a short Python function that takes a positive integer n and returns
# the sum of the squares of all the odd positive integers smaller than n.
# R-1.7 Give a single command that computes the sum from Exercise R-1.6, rely-
# ing on Python’s comprehension syntax and the built-in sum function.
# R-1.8 Python allows negative integers to be used as indices into a sequence,
# such as a string. If string s has length n, and expression s[k] is used for in-
# dex −n ≤ k < 0, what is the equivalent index j ≥ 0 such that s[j] references
# the same element?
# R-1.9 What parameters should be sent to the range constructor, to produce a
# range with values 50, 60, 70, 80?
# R-1.10 What parameters should be sent to the range constructor, to produce a
# range with values 8, 6, 4, 2, 0, −2, −4, −6, −8?
# R-1.11 Demonstrate how to use Python’s list comprehension syntax to produce
# the list [1, 2, 4, 8, 16, 32, 64, 128, 256].
# R-1.12 Python’s random module includes a function choice(data) that returns a
# random element from a non-empty sequence. The random module in-
# cludes a more basic function randrange, with parameterization similar to
# the built-in range function, that return a random choice from the given
# range. Using only the randrange function, implement your own version
# of the choice function.
# C-1.13 Write a pseudo-code description of a function that reverses a list of n
# integers, so that the numbers are listed in the opposite order than they
# were before, and compare this method to an equivalent Python function
# for doing the same thing.
# C-1.14 Write a short Python function that takes a sequence of integer values and
# determines if there is a distinct pair of numbers in the sequence whose
# product is odd.
# C-1.15 Write a Python function that takes a sequence of numbers and determines
# if all the numbers are different from each other (that is, they are distinct).
# C-1.16 In our implementation of the scale function (page 25), the body of the loop
# executes the command data[j] = factor. We have discussed that numeric
# types are immutable, and that use of the = operator in this context causes
# the creation of a new instance (not the mutation of an existing instance).
# How is it still possible, then, that our implementation of scale changes the
# actual parameter sent by the caller?
# C-1.17 Had we implemented the scale function (page 25) as follows, does it work
# properly?
# def scale(data, factor):
#   for val in data:
#     val = factor
# Explain why or why not.
# C-1.18 Demonstrate how to use Python’s list comprehension syntax to produce
# the list [0, 2, 6, 12, 20, 30, 42, 56, 72, 90].
# C-1.19 Demonstrate how to use Python’s list comprehension syntax to produce
# the list [ a , b , c , ..., z ], but without having to type all 26 such
# characters literally.
# C-1.20 Python’s random module includes a function shuﬄe(data) that accepts a
# list of elements and randomly reorders the elements so that each possi-
# ble order occurs with equal probability. The random module includes a
# more basic function randint(a, b) that returns a uniformly random integer
# from a to b (including both endpoints). Using only the randint function,
# implement your own version of the shuﬄe function.
# C-1.21 Write a Python program that repeatedly reads lines from standard input
# until an EOFError is raised, and then outputs those lines in reverse order
# (a user can indicate end of input by typing ctrl-D).
# C-1.22 Write a short Python program that takes two arrays a and b of length n
# storing int values, and returns the dot product of a and b. That is, it returns
# an array c of length n such that c[i] = a[i] · b[i], for i = 0, . . . , n − 1.
# C-1.23 Give an example of a Python code fragment that attempts to write an ele-
# ment to a list based on an index that may be out of bounds. If that index
# is out of bounds, the program should catch the exception that results, and
# print the following error message:
# “Don’t try buffer overflow attacks in Python!”
# C-1.24 Write a short Python function that counts the number of vowels in a given
# character string.
# C-1.25 Write a short Python function that takes a string s, representing a sentence,
# and returns a copy of the string with all punctuation removed. For exam-
# ple, if given the string "Let s try, Mike.", this function would return
# "Lets try Mike".
# C-1.26 Write a short program that takes as input three integers, a, b, and c, from
# the console and determines if they can be used in a correct arithmetic
# formula (in the given order), like “a + b = c,” “a = b − c,” or “a ∗ b = c.”
# C-1.27 In Section 1.8, we provided three different implementations of a generator
# that computes factors of a given integer. The third of those implementa-
# tions, from page 41, was the most efﬁcient, but we noted that it did not
# yield the factors in increasing order. Modify the generator so that it reports
# factors in increasing order, while maintaining its general performance ad-
# vantages.
# P-1.29 Write a Python program that outputs all possible strings formed by using
# the characters c , a , t , d , o , and g exactly once.
# P-1.30 Write a Python program that can take a positive integer greater than 2 as
# input and write out the number of times one must repeatedly divide this
# number by 2 before getting a value less than 2.
# P-1.31 Write a Python program that can “make change.” Your program should
# take two numbers as input, one that is a monetary amount charged and the
# other that is a monetary amount given. It should then return the number
# of each kind of bill and coin to give back as change for the difference
# between the amount given and the amount charged. The values assigned
# to the bills and coins can be based on the monetary system of any current
# or former government. Try to design your program so that it returns as
# few bills and coins as possible.
# P-1.32 Write a Python program that can simulate a simple calculator, using the
# console as the exclusive input and output device. That is, each input to the
# calculator, be it a number, like 12.34 or 1034, or an operator, like + or =,
# can be done on a separate line. After each such input, you should output
# to the Python console what would be displayed on your calculator.
# P-1.33 Write a Python program that simulates a handheld calculator. Your pro-
# gram should process input from the Python console representing buttons
# that are “pushed,” and then output the contents of the screen after each op-
# eration is performed. Minimally, your calculator should be able to process
# the basic arithmetic operations and a reset/clear operation.
# P-1.34 A common punishment for school children is to write out a sentence mul-
# tiple times. Write a Python stand-alone program that will write out the
# following sentence one hundred times: “I will never spam my friends
# again.” Your program should number each of the sentences and it should
# make eight different random-looking typos.
# P-1.35 The birthday paradox says that the probability that two people in a room
# will have the same birthday is more than half, provided n, the number of
# people in the room, is more than 23. This property is not really a paradox,
# but many people ﬁnd it surprising. Design a Python program that can test
# this paradox by a series of experiments on randomly generated birthdays,
# which test this paradox for n = 5, 10, 15, 20, . . . , 100.
# P-1.36 Write a Python program that inputs a list of words, separated by white-
# space, and outputs how many times each word appears in the list. You
# need not worry about efﬁciency at this point, however, as this topic is
# something that will be addressed later in this book.

print( "Welcome to the GPA calculator." )
print( "Please enter all your letter grades, one per line." )
print( "Enter a blank line to designate the end." )
# map from letter grade to point value
points = { "A+" :4.0, "A" :4.0, "A-" :3.67, "B+" :3.33, "B" :3.0, "B-" :2.67,
"C+" :2.33, "C" :2.0, "C" :1.67, "D+" :1.33, "D" :1.0, "F" :0.0}
num_courses = 0
total_points = 0
done = False
while not done:
  grade = input()
  if grade == "":
    done = True
  elif grade not in points:
    print(f"Unkown grade {grade} not in the points")
  else:
    num_courses += 1
    total_points += points[grade]
if num_courses > 0:
  print(f'Your GPA is {total_points/num_courses}')

temperature  = 98.6

# 9temperature
# False
original = temperature
temperature = temperature + 5.0

temperature,original

bool()

bool(24>23)

bool(23>24)

int()

int('334')

# int('hello')
int(-3.12)
int(-3.89)

int('7f',16)

float()

float('3.14')

str_one = 'hello'
str("hello")

str_one.upper()

str_one.capitalize()

str_one[1]

list_one = list(str_one)

list_one

list_one[1] = 'a'

list_one

tuple_one = str_one,

# tuple_one[0] = 'a'

tuple_two = list_one,

tuple_two

set_one = set(str_one)

set_one

frozenset(set_one)

points['A']

list_one = [1,2,4,5]

if 3 in list_one:
  print("3 is not in list one")
elif 1 in list_one:
  print("winner")
else:
  print("3 is in list one")

for i in list_one:
  print(i)

j = 0
while j < len(list_one):
  j += 1

j

"""## DataBases"""

!pip install sqlalchemy psycopg2



from sqlalchemy import create_engine, text

# Database connection parameters
hostname = '34.148.197.101'
port = '5432'
database_name = 'forumdb'
username = 'postgres'
password = 'boostedchat'

# Create the connection string
connection_string = f'postgresql+psycopg2://{username}:{password}@{hostname}:{port}/{database_name}'

# Create the SQLAlchemy engine
engine = create_engine(connection_string)

def make_query(query):
  with engine.connect() as connection:
    # Execute a query
    result = connection.execute(text(query))
    print(result)
    connection.commit()
  return


def make_query_with_records(query):
  with engine.connect() as connection:
    # Execute a query
    result = connection.execute(text(query))
    # print(result)
    connection.commit()
    records = result.fetchall()
    print(records)
  return records

make_query("""
create table if not exists users(
  pk int generated always as identity,
  username text not null,
  gecko_points text,
  email text not null,
  primary key (pk),
  unique(username)
);
""")

make_query("""
create temp table if not exists temp_users(
  pk int generated always as identity,
  username text not null,
  gecko_points text,
  email text not null,
  primary key (pk),
  unique(username)
);
""")

make_query("""
insert into users (username, gecko_points, email) values ('zarry', 'No geckos', 'zarryochola@gmail.com');
""")
make_query("""
insert into users (username, gecko_points, email) values ('bossman','No geckos', 'boseric01@gmail.com');
""")

records = make_query_with_records("""
 select * from users order by username
""")

records[0][3]

make_query("""
create table if not exists categories(
  pk int generated always as identity,
  title text not null,
  description text,
  primary key (pk)
);
""")

make_query("""
insert into categories (title, description) values ('apple','fruits'),('oranage','fruit'),('lettuce','vegetable');
""")

records = make_query_with_records("""
select * from categories
""")

records = make_query_with_records("""
select * from categories where description = 'vegetable';
""")

records = make_query_with_records("""
select * from categories where description = 'fruit' order by title;
""")

make_query("""
update categories set description = 'fruit' where description = 'fruits';
""")

records = make_query_with_records("""
select * from categories where description = 'fruit' order by title;
""")

records = make_query_with_records("""
select * from categories where description = 'fruit' order by title desc;
""")

records = make_query_with_records("""
select * from categories where description = 'fruit' order by title asc;
""")

make_query("""
insert into categories (title) values ('lemon');
""")

records = make_query_with_records("""
select * from categories;
""")

records = make_query_with_records("""
select * from categories where description is not null;
""")

records = make_query_with_records("""
select * from categories where description is null;
""")

records = make_query_with_records("""
select * from categories order by description NULLS FIRST;
""")

records = make_query_with_records("""
select * from categories order by description NULLS LAST;
""")

## assignment 1 -  update the values of all the lines for which the description is vegetable put their title to 'no title'
make_query("""

""")

make_query("""
insert into categories (title, description) values ('peach','fruit');
""")

make_query("""
delete from categories where title = 'peach';
""")

records = make_query_with_records("""
select * from categories;
""")

"""## Assignments"""

# returns all records that have pk> 2.
# find all records that have a title field value starting with the letter 'a'.
# find all records with titles ending with the letter e,
# search all records that contain the letters 'ap'
# search all records that start with A using upper case
# return only distinct (different) values for the descriptions NB: be careful how you work with nulls
# If we want the two first records that were inserted, perform query to do that
# If we only want the second record that was inserted, perform query to do that
# search for all categories that have the value pk=6 or the value pk=4,



"""# Time Series"""

import numpy as np
import pandas as pd
from datetime import datetime

now = datetime.now()

now

delta = datetime(2024,1,7) - datetime(2022,6,30,8,15)

delta

start = datetime(2024,10,8)

from datetime import timedelta

start + timedelta(days=12)

start - 2 * timedelta(days=12)

str(start)

# (ISO C89 compatible)
start.strftime("%Y-%m-%d")

start.strftime("%y-%m-%d: %I:%M:%S")

datestrs = ["2011-07-06 12:00:00", "2011-08-06 00:00:00"]

pd.to_datetime(datestrs)

df = pd.DataFrame(pd.to_datetime(datestrs))

df

df[0][1]

dates = []
for i in range(0,100):
  dates.append(datetime(2024,9,3) + timedelta(days=i))

len(dates)

ts = pd.Series(np.random.randn(len(dates)), index=dates)

from matplotlib import pyplot as plt
plt.plot(ts)

ts.index

plt.plot(ts[::2])

# research note: research on different probability distributions
longer_ts = pd.Series(np.random.randn(1000),index = pd.date_range(start = "2022,01,01", periods=1000))

plt.plot(longer_ts)

longer_ts["2022-02-05"]

longer_ts["2022-02-05":"2022-02-10"]

longer_ts.truncate(after="2022-02-28")

dates = pd.date_range("2022-01-01",periods=100, freq="W-WED")
l_df = pd.DataFrame(np.random.standard_normal((100,4)),index=dates,columns=["Nairobi","Kwale","Kisii","Busia"])

l_df

plt.plot(l_df.loc["2022-08-01":"2022-10-01"])

plt.plot(l_df.loc["2023-08-01":"2023-10-01"])

dates

"""## Assignment"""

# truncate after august 2022 and plot the results
# check if there are any duplicates in the dataset
# Suppose you wanted to aggregate the data having nonunique timestamps. how would one do it,
# generate dates from oct 2022 to december 2022 containing the last business day of each month
# normalized the generated dates to midnight as a convention.
# return the same dataset but now the interval let it be after every 1 and 1/2 hours
# shift the dataset 2 months ahead
# shift the dataset 90 minutes backward
# roll the dates forward by one month and find the mean

"""## Statistical Modeling"""

!pip install statsmodels --quiet

import pandas as pd

data = pd.DataFrame({
        'x0': [1, 2, 3, 4, 5],
        'x1': [0.01, -0.01, 0.25, -4.1, 0.],
        'y': [-1.5, 0., 3.6, 1.3, -2.]
      })

data

data.columns

data.to_numpy()

df2  = data

df2['strings'] = ['a', 'b', 'c', 'd', 'e']  # add a new column

df2.to_numpy()

df2['category'] = pd.Categorical(['a', 'b', 'a', 'a', 'b'],categories=['a','b'])  # add a new column

df2 = df2.drop('strings', axis=1)

dummies = pd.get_dummies(df2['category'], prefix='categ')
data_with_dummies = df2.drop('category', axis=1).join(dummies)
data_with_dummies

data_with_dummies['categ_a'] = data_with_dummies['categ_a'].astype(int)
data_with_dummies['categ_b'] = data_with_dummies['categ_b'].astype(int)
data_with_dummies

data_with_dummies.to_numpy()

data.columns

# y = mx + c
# y = m1x0 + m2x1 +c
data = pd.DataFrame({
        'x0': [1, 2, 3, 4, 5],
        'x1': [0.01, -0.01, 0.25, -4.1, 0.],
        'y': [-1.5, 0., 3.6, 1.3, -2.]
      })

data

import patsy

y, X  = patsy.dmatrices('y ~ x0 + x1', data)

y

X

patsy.dmatrices('y ~ x0 + x1 + 0', data)[1]

import numpy as np

coef,resid, _,_ = np.linalg.lstsq(X,y)

coef = pd.Series(coef.squeeze(), index=X.design_info.column_names)
coef

# y = mx + c
# y = m0x0 + m1x1 + c
# y = -0.079106 * x0 + -0.265464 * x2 + 0.312910
df3 = data.copy()
df3['y'] = 0.312910 + (-0.079106 * df3['x0']) + (-0.265464 * df3['x1'])
df3

data

import statsmodels.api as sm
import statsmodels.formula.api as smf

rng = np.random.default_rng(seed=12345)

def dnorm(mean, variance, size=1):
    if isinstance(size, int):
        size = size,
    return mean + np.sqrt(variance) * rng.standard_normal(size)

N = 100
X = np.c_[dnorm(0, 0.4, size=N),
          dnorm(0, 0.6, size=N),
          dnorm(0, 0.2, size=N)]
X

import matplotlib.pyplot as plt
plt.bar(X[:,0],range(100))

eps = dnorm(0,0.1,size=N)

beta = [0.1,0.3,0.5]
y = np.dot(X,beta) + eps

y

X_model = sm.add_constant(X)

model = sm.OLS(y,X)

results = model.fit()

results.summary()



from statsmodels.tsa.ar_model import AutoReg

MAXLAGS = 5

longer_ts = pd.Series(np.random.randn(1000),index = pd.date_range(start = "2022,01,01", periods=1000))

model = AutoReg(longer_ts.values,MAXLAGS)

results_ts = model.fit()

results.summary()

predictions = results.predict(np.array(longer_ts.values[0:3].tolist()).reshape(3,))

predictions

real_value = longer_ts.values[4]

predictions - real_value

"""## Assignment"""

# go and perform the following transformations on the data above
# a)  y ~ x0 + np.log(np.abs(x1) + 1)
# b)  y ~ standardize(x0) + center(x1)
# and fit your data to those above transformations
# create categorical data based on x1,x2,..etc
# y ~ x1 + x2 + .....
# give very elaborate explanations of the summaries in docstring format

"""## Modelling Data with Machine Learning Models"""



!pip install scikit-learn --quiet

import seaborn as sns

iris  = sns.load_dataset('iris')

iris.head()

sns.set()
sns.pairplot(iris,hue='species',height=1.5);

X_iris = iris.drop('species',axis=1)

X_iris.columns

y_iris = iris['species']

y_iris

from sklearn.model_selection import train_test_split
Xtrain, Xtest, ytrain, ytest = train_test_split(X_iris,y_iris,random_state=1)

150-112

Xtest.shape

from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(Xtrain,ytrain)
y_model = model.predict(Xtest)

from sklearn.metrics import accuracy_score
accuracy_score(ytest,y_model)

from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=1)
model.fit(Xtrain,ytrain)
y_model = model.predict(Xtest)
accuracy_score(ytest,y_model)

from sklearn.decomposition import PCA
model = PCA(n_components=2)
model.fit(X_iris)
X_2d = model.transform(X_iris)

X_2d.shape

X_iris.shape

iris['PCA1'] = X_2d[:,0]
iris['PCA2'] = X_2d[:,1]
sns.lmplot(data=iris,x='PCA1',y='PCA2',hue='species',fit_reg=False);

from sklearn.mixture import GaussianMixture as GMM
model = GMM(n_components=3,covariance_type='full')
model.fit(X_iris)
y_gmm = model.predict(X_iris)
iris['cluster'] = y_gmm
sns.lmplot(data=iris,x='PCA1',y='PCA2',hue='species',col='cluster',fit_reg=False);

from sklearn.datasets import load_digits
digits = load_digits()
digits.images.shape

digits.images[0].shape

import matplotlib.pyplot as plt
fig,axes = plt.subplots(10,10,figsize=(8,8),subplot_kw={'xticks':[],'yticks':[]},gridspec_kw=dict(hspace=0.1,wspace=0.1))
for i,ax in enumerate(axes.flat):
    ax.imshow(digits.images[i],cmap='binary',interpolation='nearest')
    ax.text(0.05,0.05,str(digits.target[i]),transform=ax.transAxes,color='red')
    print(digits.target[i])
    print(digits.images[i][-1])
    # print(accuracy_score(digits.images[i],digits.target[i]))

digits.target

"""## Assignment"""

#Load the iris dataset from sklearn.datasets and split it into training and testing sets.
#Use the KNeighborsClassifier from sklearn.neighbors to train a model on the training data.
#Evaluate the performance of the KNeighborsClassifier model on the testing data using accuracy score, confusion matrix, and classification report.
#Use the DecisionTreeClassifier from sklearn.tree to train a model on the training data.
#Evaluate the performance of the DecisionTreeClassifier model on the testing data using accuracy score, confusion matrix, and classification report.
#Compare the performance of the KNeighborsClassifier and DecisionTreeClassifier models.
#Use the StandardScaler from sklearn.preprocessing to standardize the features in the iris dataset.
#Train a new KNeighborsClassifier model on the standardized training data.
#Evaluate the performance of the standardized KNeighborsClassifier model on the standardized testing data.
#Compare the performance of the standardized KNeighborsClassifier model with the original model.
#Use the LogisticRegression from sklearn.linear_model to train a model on the training data.
#Evaluate the performance of the LogisticRegression model on the testing data using accuracy score, confusion matrix, and classification report.
#Compare the performance of the LogisticRegression model with the KNeighborsClassifier and DecisionTreeClassifier models.
#Use the GridSearchCV from sklearn.model_selection to tune the hyperparameters of the KNeighborsClassifier model.
#Use the RandomForestClassifier from sklearn.ensemble to train a model on the training data and evaluate its performance on the testing data. Compare its performance with the other models.

"""## Deep Learning"""

import torch

#z = sum([x*w for x,w in zip(inputs,weights)]) + bias
# pass in for multiple inputs

from torch import tensor

matrix_1 = [
    [1,2,1],
    [8,1,2],
    [2,5,4]
]
m1 = torch.tensor(matrix_1)
matrix_2 = [
    [2,3],
    [6,7],
    [1,8]
]
m2 = torch.tensor(matrix_2)

def matmul(a,b):
  ar,ac = a.shape
  br,bc = b.shape
  assert ac == br
  c = torch.zeros(ar,bc)
  for i in range(ar): # Assignment: remain with only one for loop
    for j in range(bc):
      for k in range(ac):
        c[i,j] += a[i,k] * b[k,j]
  return c

result = matmul(m1,m2)
result

m1huge = torch.randn(5,28*28)
m2huge = torch.randn(784,10)

matmul_result = matmul(m1huge,m2huge)
matmul_result

result_two = m1 @ m2
result_two



layer_one = None
layer_two = None
layer_three = None

def lin(x, w, b): return matmul(x, w) + b


x = torch.randn(200,100)
y = torch.randn(200)

w1 = torch.randn(100,50)
b1 = torch.randn(50)
w2 = torch.randn(50,1)
b2 = torch.randn(1)


layer_one = lin(x,w1,b1)

layer_one

layer_one.shape

layer_one.mean(),layer_one.std()

def relu(x): return x.clamp_min(0.)

layer_two = relu(layer_one)

layer_two.mean(),layer_two.std()

def lunyamwi_model(x):
  layer_one = lin(x,w1,b1)
  layer_two = relu(layer_one)
  layer_three = lin(layer_two,w2,b2)
  return layer_three

final_result = lunyamwi_model(x)

final_result.mean(), final_result.std()

"""### Assignment"""

# 0. Remain with one for loop in matmul function in order for it to run faster
# 1. Write the Python code to implement a single neuron.
# 2. Write the Python code to implement ReLU.
# 3. Write the Python code for a dense layer in terms of matrix multiplication.
# 4. Write the Python code for a dense layer in plain Python (that is, with list compre‐
# hensions and functionality built into Python).
# 5. What is the “hidden size” of a layer?
# 6. What does the t method do in PyTorch?
# 7. Why is matrix multiplication written in plain Python very slow?
# 8. In matmul, why is ac==br?
# 9. In Jupyter Notebook, how do you measure the time taken for a single cell to
# execute?
# 10. What is elementwise arithmetic?
# 11. Write the PyTorch code to test whether every element of a is greater than the cor‐
# responding element of b.
# 12. What is a rank-0 tensor? How do you convert it to a plain Python data type?
# 13. What does this return, and why?
# tensor([1,2]) + tensor([1])
# 14. What does this return, and why?
# tensor([1,2]) + tensor([1,2,3])

"""## Convolutions"""

from __future__ import absolute_import, division, print_function

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

# tf.logging.set_verbosity(tf.logging.ERROR)

tf.__version__

!pip install keras

tf.keras.__version__



from tensorflow.keras import layers, datasets, models, optimizers


model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])


((train_data, train_labels), (test_data, test_labels)) = tf.keras.datasets.mnist.load_data()
train_data = train_data/np.float32(255)
test_data = test_data/np.float32(255)
eval_data = test_data
eval_labels = np.asarray(test_labels, dtype=np.int32)
model.fit(train_data, train_labels, epochs=5, validation_data=(eval_data, eval_labels))

test_loss, test_accuracy = model.evaluate(eval_data, eval_labels)
print('Test accuracy:', test_accuracy)



import torch
import torch.nn as nn
import torch.optim as optim
import torch
from torchvision import datasets, transforms

# Define the model using nn.Sequential
model = nn.Sequential(
    nn.Conv2d(1, 32, kernel_size=(3, 3)),  # Input channels = 1, Output channels = 32
    nn.ReLU(),  # Activation function applied here
    nn.MaxPool2d(kernel_size=(2, 2)),
    nn.Conv2d(32, 64, kernel_size=(3, 3)),
    nn.ReLU(),
    nn.MaxPool2d(kernel_size=(2, 2)),
    nn.Conv2d(64, 64, kernel_size=(3, 3)),
    nn.ReLU(),
    nn.Flatten(),
    nn.Linear(64 * 3 * 3, 64),  # Adjust input size based on the output shape of the last Conv layer
    nn.ReLU(),
    nn.Linear(64, 10),  # Output layer for 10 classes
)

# Compile the model (PyTorch doesn't have a compile method like Keras)
# Define loss function and optimizer
loss_fn = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters())


# Load the MNIST dataset
train_dataset = datasets.MNIST(root='./data', train=True, transform=transforms.ToTensor(), download=True)
eval_dataset = datasets.MNIST(root='./data', train=False, transform=transforms.ToTensor(), download=True)

# Create data loaders
train_loader = torch.utils.data.DataLoader(dataset=train_dataset, batch_size=64, shuffle=True)
eval_loader = torch.utils.data.DataLoader(dataset=eval_dataset, batch_size=64, shuffle=False)

# Get the data and labels for the first batch
train_data, train_labels = next(iter(train_loader))
eval_data, eval_labels = next(iter(eval_loader))

# Training loop (assuming train_data and train_labels are already defined)
# Training loop (assuming train_loader and test_loader are defined)
epochs = 5
for epoch in range(epochs):
    model.train()
    running_loss = 0.0
    correct = 0
    total = 0

    for images, labels in train_loader:
        optimizer.zero_grad()  # Clear gradients
        outputs = model(images)  # Forward pass
        loss = loss_fn(outputs, labels)  # Compute loss
        loss.backward()  # Backward pass
        optimizer.step()  # Update weights

        running_loss += loss.item()
        _, predicted = outputs.max(1)  # Get the index of the max log-probability
        total += labels.size(0)
        correct += predicted.eq(labels).sum().item()

    accuracy = correct / total
    print(f'Epoch [{epoch + 1}/{epochs}], Loss: {running_loss / len(train_loader):.4f}, Accuracy: {accuracy:.4f}')

# Evaluation on test set
model.eval()
with torch.no_grad():
    test_correct = 0
    test_total = 0
    for images, labels in eval_loader:
        outputs = model(images)
        _, predicted = outputs.max(1)
        test_total += labels.size(0)
        test_correct += predicted.eq(labels).sum().item()

    test_accuracy = test_correct / test_total
    print('Test accuracy:', test_accuracy)

"""## Assignment"""

# 1. Write a Tensorflow code snippet to implement a simple feedforward neural network with one input layer, one hidden layer, and one output layer. The input layer should have 10 nodes, the hidden layer should have 5 nodes, and the output layer should have 1 node. Use the sigmoid activation function for the hidden layer and the identity activation function for the output layer.
# 2. Write a Tensorflow code snippet to implement the mean squared error loss function for a regression problem.
# 3. Write a Tensorflow code snippet to implement the softmax activation function for a multi-class classification problem.
# 4. Write a Tensorflow code snippet to implement the ReLU activation function for a convolutional neural network.
# 5. Write a Tensorflow code snippet to implement the dropout regularization technique for a neural network. The dropout probability should be 0.5.
# 6. Write a PyTorch code snippet to implement a simple feedforward neural network with one input layer, one hidden layer, and one output layer. The input layer should have 10 nodes, the hidden layer should have 5 nodes, and the output layer should have 1 node. Use the sigmoid activation function for the hidden layer and the identity activation function for the output layer.
# 7. Write a PyTorch code snippet to implement the mean squared error loss function for a regression problem.
# 8. Write a PyTorch code snippet to implement the softmax activation function for a multi-class classification problem.
# 9. Write a PyTorch code snippet to implement the ReLU activation function for a convolutional neural network.
# 10. Write a PyTorch code snippet to implement the dropout regularization technique for a neural network. The dropout probability should be 0.5.

"""### Natural Language Processing"""

import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from collections import Counter
import numpy as np

# Example sentences and labels
sentences = [
    "I love this product",
    "This is the worst thing I have ever bought",
    "Absolutely fantastic! Highly recommend.",
    "Not worth the money",
    "I am very satisfied with my purchase",
    "Terrible experience, will not buy again"
]

labels = ["positive", "negative", "positive", "negative", "positive", "negative"]

# Preprocess the text data
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)
sequences = tokenizer.texts_to_sequences(sentences)

# Encode labels to integers
label_encoder = LabelEncoder()
encoded_labels = label_encoder.fit_transform(labels)

# Pad sequences to ensure uniform input size (e.g., max length of 5)
max_length = 5
padded_sequences = pad_sequences(sequences, maxlen=max_length, padding='post')

# Split into training and test sets
train_texts, test_texts, train_labels, test_labels = train_test_split(padded_sequences, encoded_labels, test_size=0.2)

# Define hyperparameters
vocab_size = len(tokenizer.word_index) + 1  # Size of vocabulary (plus one for padding)
embedding_dim = 10  # Size of each embedding vector
hidden_size = 128   # Number of features in hidden state
output_size = len(set(labels))  # Number of classes (for binary classification)
num_layers = 1     # Number of stacked RNN layers

# Define the RNN model
model = Sequential([
    Embedding(vocab_size, embedding_dim, input_length=max_length),  # Embedding layer
    SimpleRNN(hidden_size),  # RNN layer
    Dense(output_size, activation='softmax')  # Fully connected layer
])

# Define loss function and optimizer
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy()
optimizer = tf.keras.optimizers.Adam()

# Compile the model
model.compile(loss=loss_fn, optimizer=optimizer, metrics=['accuracy'])

# Training loop
epochs = 5
model.fit(train_texts, train_labels, epochs=epochs, batch_size=2, shuffle=True)



import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from collections import Counter
import numpy as np

# Define the RNN model
class RNNModel(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_size, output_size, num_layers=1):
        super(RNNModel, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim)  # Embedding layer
        self.rnn = nn.RNN(embedding_dim, hidden_size, num_layers, batch_first=True)  # RNN layer
        self.fc = nn.Linear(hidden_size, output_size)  # Fully connected layer

    def forward(self, x):
        x = self.embedding(x)  # Convert indices to embeddings
        out, _ = self.rnn(x)  # Forward propagate RNN
        out = out[:, -1, :]  # Get the last time step's output
        out = self.fc(out)  # Pass through the fully connected layer
        return out

# Example sentences and labels
sentences = [
    "I love this product",
    "This is the worst thing I have ever bought",
    "Absolutely fantastic! Highly recommend.",
    "Not worth the money",
    "I am very satisfied with my purchase",
    "Terrible experience, will not buy again"
]

labels = ["positive", "negative", "positive", "negative", "positive", "negative"]

# Preprocess the text data
def preprocess(sentences):
    tokenized_sentences = [s.lower().split() for s in sentences]
    all_words = [word for sentence in tokenized_sentences for word in sentence]
    word_counts = Counter(all_words)

    # Create a mapping of words to indices (starting from index 1)
    word_to_index = {word: i + 1 for i, (word, _) in enumerate(word_counts.items())}

    # Convert sentences to sequences of indices
    sequences = [[word_to_index[word] for word in sentence] for sentence in tokenized_sentences]

    return sequences, word_to_index

# Convert sentences to sequences of indices
sequences, word_to_index = preprocess(sentences)

# Encode labels to integers
label_encoder = LabelEncoder()
encoded_labels = label_encoder.fit_transform(labels)

# Pad sequences to ensure uniform input size (e.g., max length of 5)
max_length = 5
padded_sequences = np.array([seq + [0] * (max_length - len(seq)) if len(seq) < max_length else seq[:max_length] for seq in sequences])

# Create dataset and dataloader
class TextDataset(Dataset):
    def __init__(self, texts, labels):
        self.texts = texts  # Padded sequences
        self.labels = labels  # Corresponding labels

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        return torch.tensor(self.texts[idx], dtype=torch.long), torch.tensor(self.labels[idx], dtype=torch.long)

# Split into training and test sets
train_texts, test_texts, train_labels, test_labels = train_test_split(padded_sequences, encoded_labels, test_size=0.2)

train_dataset = TextDataset(train_texts.tolist(), train_labels.tolist())
test_dataset = TextDataset(test_texts.tolist(), test_labels.tolist())

train_loader = DataLoader(dataset=train_dataset, batch_size=2, shuffle=True)
test_loader = DataLoader(dataset=test_dataset, batch_size=2, shuffle=False)

# Define hyperparameters
vocab_size = len(word_to_index) + 1  # Size of vocabulary (plus one for padding)
embedding_dim = 10  # Size of each embedding vector
hidden_size = 128   # Number of features in hidden state
output_size = len(set(labels))  # Number of classes (for binary classification)
num_layers = 1     # Number of stacked RNN layers

# Instantiate the model
model = RNNModel(vocab_size, embedding_dim, hidden_size, output_size, num_layers)

# Define loss function and optimizer
loss_fn = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters())

# Training loop
epochs = 5
for epoch in range(epochs):
    model.train()
    running_loss = 0.0

    for inputs, labels in train_loader:
        optimizer.zero_grad()  # Clear gradients

        outputs = model(inputs)  # Forward pass

        loss = loss_fn(outputs, labels)  # Compute loss
        loss.backward()  # Backward pass
        optimizer.step()  # Update weights

        running_loss += loss.item()

    print(f'Epoch [{epoch + 1}/{epochs}], Loss: {running_loss / len(train_loader):.4f}')

# Evaluation on test set (not implemented here; would follow similar structure)

"""### Large Language Models"""

# import tensorflow as tf
# from tensorflow.keras import layers, Model, Sequential
# import numpy as np
# import random

# # Define the GPT Block (Transformer Block) in Keras
# class GPTBlock(layers.Layer):
#     def __init__(self, embedding_dim, n_heads):
#         super(GPTBlock, self).__init__()
#         self.attention = layers.MultiHeadAttention(num_heads=n_heads, key_dim=embedding_dim)
#         self.ln1 = layers.LayerNormalization()
#         self.feed_forward = Sequential([
#             layers.Dense(4 * embedding_dim, activation='relu'),
#             layers.Dense(embedding_dim)
#         ])
#         self.ln2 = layers.LayerNormalization()

#     def call(self, x):
#         attn_output = self.attention(x, x)
#         x = self.ln1(x + attn_output)  # Residual connection
#         ff_output = self.feed_forward(x)
#         return self.ln2(x + ff_output)  # Residual connection

# # Define the Simple GPT Model
# class SimpleGPT(Model):
#     def __init__(self, num_blocks, embedding_dim, n_heads, vocab_size=256):
#         super(SimpleGPT, self).__init__()
#         self.embedding = layers.Embedding(vocab_size, embedding_dim)
#         self.blocks = [GPTBlock(embedding_dim, n_heads) for _ in range(num_blocks)]
#         self.fc_out = layers.Dense(vocab_size)

#     def call(self, x):
#         x = self.embedding(x)
#         for block in self.blocks:
#             x = block(x)
#         return self.fc_out(x)

# # Sample text data for demonstration
# text_data = "hello world this is a simple gpt model example using tensorflow " * 1000  # Repeated to increase size

# # Create a character-level dataset
# class TextDataset(tf.data.Dataset):
#     def __new__(cls, text, seq_length, batch_size):
#         chars = sorted(set(text))
#         char_to_idx = {ch: idx for idx, ch in enumerate(chars)}
#         idx_to_char = {idx: ch for idx, ch in enumerate(chars)}

#         sequences = []
#         targets = []
#         for i in range(len(text) - seq_length):
#             input_seq = text[i:i + seq_length]
#             target_seq = text[i + 1:i + seq_length + 1]
#             sequences.append([char_to_idx[ch] for ch in input_seq])
#             targets.append([char_to_idx[ch] for ch in target_seq])

#         dataset = tf.data.Dataset.from_tensor_slices((sequences, targets))
#         return dataset.batch(batch_size, drop_remainder=True), char_to_idx, idx_to_char

# # Hyperparameters
# seq_length = 30
# batch_size = 64
# learning_rate = 0.001
# epochs = 5
# embedding_dim = 128
# n_heads = 4
# num_blocks = 2

# # Create dataset
# dataset, char_to_idx, idx_to_char = TextDataset(text_data, seq_length, batch_size)

# # Instantiate the model, optimizer, and loss function
# model = SimpleGPT(num_blocks=num_blocks, embedding_dim=embedding_dim, n_heads=n_heads, vocab_size=len(char_to_idx))
# optimizer = tf.keras.optimizers.Adam(learning_rate=learning_rate)
# loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

# # Training loop
# for epoch in range(epochs):
#     running_loss = 0.0
#     for inputs, targets in dataset:
#         with tf.GradientTape() as tape:
#             outputs = model(inputs, training=True)  # Forward pass
#             loss = loss_fn(targets, outputs)  # Compute loss

#         gradients = tape.gradient(loss, model.trainable_variables)
#         optimizer.apply_gradients(zip(gradients, model.trainable_variables))
#         running_loss += loss.numpy()

#     print(f'Epoch [{epoch + 1}/{epochs}], Loss: {running_loss / len(dataset):.4f}')

# # Function to generate text from a prompt
# def generate_text(model, start_str='hello', gen_length=50):
#     input_seq = tf.constant([char_to_idx[ch] for ch in start_str], dtype=tf.int32)
#     input_seq = tf.expand_dims(input_seq, 0)
#     generated_text = start_str

#     for _ in range(gen_length):
#         output_logits = model(input_seq)
#         next_char_probs = tf.nn.softmax(output_logits[:, -1, :], axis=-1)
#         next_char_idx = np.random.choice(len(char_to_idx), p=next_char_probs.numpy().flatten())
#         generated_text += idx_to_char[next_char_idx]

#         # Update the input sequence
#         input_seq = tf.concat([input_seq[:, 1:], tf.constant([[next_char_idx]], dtype=tf.int32)], axis=1)

#     return generated_text

# # Generate text from a prompt
# generated_text = generate_text(model, start_str='hello', gen_length=100)
# print("Generated Text:", generated_text)





import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
import numpy as np

# Define the GPT Block (Transformer Block)
class GPTBlock(nn.Module):
    def __init__(self, embedding_dim, n_heads):
        super(GPTBlock, self).__init__()
        self.attention = nn.MultiheadAttention(embedding_dim, n_heads)
        self.ln1 = nn.LayerNorm(embedding_dim)
        self.feed_forward = nn.Sequential(
            nn.Linear(embedding_dim, 4 * embedding_dim),
            nn.ReLU(),
            nn.Linear(4 * embedding_dim, embedding_dim)
        )
        self.ln2 = nn.LayerNorm(embedding_dim)

    def forward(self, x):
        attn_output, _ = self.attention(x, x, x)
        x = self.ln1(x + attn_output)  # Residual connection
        ff_output = self.feed_forward(x)
        return self.ln2(x + ff_output)  # Residual connection

# Define the Simple GPT Model
class SimpleGPT(nn.Module):
    def __init__(self, num_blocks, embedding_dim, n_heads):
        super(SimpleGPT, self).__init__()
        self.embedding = nn.Embedding(256, embedding_dim)  # Simple embedding layer for characters
        self.blocks = nn.ModuleList([GPTBlock(embedding_dim, n_heads) for _ in range(num_blocks)])
        self.fc_out = nn.Linear(embedding_dim, 256)  # Output layer for character probabilities

    def forward(self, x):
        x = self.embedding(x)  # Embed input
        for block in self.blocks:
            x = block(x)
        return self.fc_out(x)

# Sample text data for demonstration
text_data = "hello world this is a simple gpt model example using pytorch " * 1000  # Repeated to increase size

# Create a character-level dataset
class TextDataset(Dataset):
    def __init__(self, text, seq_length):
        self.text = text
        self.seq_length = seq_length
        self.chars = sorted(list(set(text)))
        self.char_to_idx = {ch: idx for idx, ch in enumerate(self.chars)}
        self.idx_to_char = {idx: ch for idx, ch in enumerate(self.chars)}

    def __len__(self):
        return len(self.text) - self.seq_length

    def __getitem__(self, idx):
        input_seq = self.text[idx:idx + self.seq_length]
        target_seq = self.text[idx + 1:idx + self.seq_length + 1]

        input_tensor = torch.tensor([self.char_to_idx[ch] for ch in input_seq], dtype=torch.long)
        target_tensor = torch.tensor([self.char_to_idx[ch] for ch in target_seq], dtype=torch.long)

        return input_tensor, target_tensor

# Hyperparameters
seq_length = 30
batch_size = 64
learning_rate = 0.001
epochs = 5
embedding_dim = 128
n_heads = 4
num_blocks = 2

# Create dataset and dataloader
dataset = TextDataset(text_data, seq_length)
train_size = int(0.8 * len(dataset))
test_size = len(dataset) - train_size

train_dataset, test_dataset = torch.utils.data.random_split(dataset, [train_size, test_size])
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

# Instantiate the model and optimizer
model = SimpleGPT(num_blocks=num_blocks, embedding_dim=embedding_dim, n_heads=n_heads)
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

# Loss function
criterion = nn.CrossEntropyLoss()

# Training loop
model.train()
for epoch in range(epochs):
    running_loss = 0.0

    for inputs, targets in train_loader:
        optimizer.zero_grad()  # Clear gradients

        outputs = model(inputs)  # Forward pass

        loss = criterion(outputs.view(-1, 256), targets.view(-1))  # Compute loss
        loss.backward()  # Backward pass

        running_loss += loss.item()
        optimizer.step()  # Update weights

    print(f'Epoch [{epoch + 1}/{epochs}], Loss: {running_loss / len(train_loader):.4f}')

# Function to generate text from a prompt
# def generate_text(model, start_str='hello', gen_length=50):
#     model.eval()
#     chars_to_generate = []

#     input_seq = torch.tensor([dataset.char_to_idx[ch] for ch in start_str], dtype=torch.long).unsqueeze(0)

#     with torch.no_grad():
#         for _ in range(gen_length):
#             output_logits = model(input_seq)
#             output_probs = torch.softmax(output_logits[:, -1], dim=-1).cpu().numpy()
#             next_char_idx = np.random.choice(len(dataset.chars), p=output_probs)
#             chars_to_generate.append(dataset.idx_to_char[next_char_idx])

#             input_seq = torch.cat((input_seq[:, 1:], torch.tensor([[next_char_idx]], dtype=torch.long)), dim=1)

#     return start_str + ''.join(chars_to_generate)

# # Generate text from a prompt
# generated_text = generate_text(model, start_str='hello', gen_length=100)
# print("Generated Text:", generated_text)



"""### Stable Diffusion"""

import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Model

# Define the VAE model
class VAE(Model):
    def __init__(self, input_dim, hidden_dim, latent_dim):
        super(VAE, self).__init__()
        # Encoder
        self.encoder = tf.keras.Sequential([
            layers.Dense(hidden_dim, activation='relu'),  # Hidden layer
            layers.Dense(latent_dim + latent_dim),  # Mean and log variance of latent space
        ])

        # Decoder
        self.decoder = tf.keras.Sequential([
            layers.Dense(hidden_dim, activation='relu'),  # Hidden layer
            layers.Dense(input_dim, activation='sigmoid'),  # Output layer
        ])

    def encode(self, x):
        mean, logvar = tf.split(self.encoder(x), num_or_size_splits=2, axis=1)
        return mean, logvar

    def reparameterize(self, mean, logvar):
        epsilon = tf.random.normal(shape=mean.shape)
        return mean + tf.exp(0.5 * logvar) * epsilon

    def decode(self, z):
        return self.decoder(z)

    def call(self, x):
        mean, logvar = self.encode(x)
        z = self.reparameterize(mean, logvar)
        reconstructed = self.decode(z)
        return reconstructed, mean, logvar

# Loss function for VAE
def loss_function(model, x, reconstructed, mean, logvar):
    # Reconstruction loss
    reconstruction_loss = tf.reduce_mean(
        tf.keras.losses.binary_crossentropy(x, reconstructed)
    )
    # KL divergence loss
    kl_loss = -0.5 * tf.reduce_mean(1 + logvar - tf.square(mean) - tf.exp(logvar))
    total_loss = reconstruction_loss + kl_loss
    return total_loss

# Hyperparameters
batch_size = 128
learning_rate = 1e-3
epochs = 10
input_dim = 784  # MNIST images are 28x28 pixels
hidden_dim = 400
latent_dim = 20

# Load MNIST dataset
(train_images, _), (test_images, _) = mnist.load_data()
train_images = train_images.reshape(-1, 784).astype("float32") / 255.0
train_dataset = tf.data.Dataset.from_tensor_slices(train_images)
train_dataset = train_dataset.shuffle(buffer_size=1024).batch(batch_size)

# Instantiate the model and optimizer
model = VAE(input_dim=input_dim, hidden_dim=hidden_dim, latent_dim=latent_dim)
optimizer = tf.keras.optimizers.Adam(learning_rate=learning_rate)

# Training loop
@tf.function
def train_step(model, x, optimizer):
    with tf.GradientTape() as tape:
        reconstructed, mean, logvar = model(x)
        loss = loss_function(model, x, reconstructed, mean, logvar)
    gradients = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(gradients, model.trainable_variables))
    return loss

for epoch in range(1, epochs + 1):
    train_loss = tf.keras.metrics.Mean()
    for train_x in train_dataset:
        loss = train_step(model, train_x, optimizer)
        train_loss(loss)
    print(f'Epoch {epoch}, Loss: {train_loss.result():.4f}')



import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

# Define the VAE model
class VAE(nn.Module):
    def __init__(self, input_dim, hidden_dim, latent_dim):
        super(VAE, self).__init__()
        # Encoder
        self.fc1 = nn.Linear(input_dim, hidden_dim)  # Hidden layer
        self.fc21 = nn.Linear(hidden_dim, latent_dim)  # Mean of latent space
        self.fc22 = nn.Linear(hidden_dim, latent_dim)  # Log variance of latent space

        # Decoder
        self.fc3 = nn.Linear(latent_dim, hidden_dim)  # Hidden layer
        self.fc4 = nn.Linear(hidden_dim, input_dim)   # Output layer

    def encode(self, x):
        h1 = torch.relu(self.fc1(x))
        return self.fc21(h1), self.fc22(h1)  # Return mean and log variance

    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5 * logvar)  # Standard deviation from log variance
        eps = torch.randn_like(std)      # Random noise
        return mu + eps * std            # Reparameterization trick

    def decode(self, z):
        h3 = torch.relu(self.fc3(z))
        return torch.sigmoid(self.fc4(h3))  # Sigmoid for output to be between 0 and 1

    def forward(self, x):
        mu, logvar = self.encode(x.view(-1, 784))  # Flatten input for MNIST (28x28)
        z = self.reparameterize(mu, logvar)
        return self.decode(z), mu, logvar

# Loss function for VAE
def loss_function(recon_x, x, mu, logvar):
    BCE = nn.functional.binary_cross_entropy(recon_x.view(-1, 784), x.view(-1, 784), reduction='sum')
    KLD = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp())  # KL Divergence
    return BCE + KLD

# Hyperparameters
batch_size = 128
learning_rate = 1e-3
epochs = 10
input_dim = 784  # MNIST images are 28x28 pixels
hidden_dim = 400
latent_dim = 20

# Load MNIST dataset
train_dataset = datasets.MNIST(root='./data', train=True, transform=transforms.ToTensor(), download=True)
train_loader = DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=True)

# Instantiate the model and optimizer
model = VAE(input_dim=input_dim, hidden_dim=hidden_dim, latent_dim=latent_dim)
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

# Training loop
model.train()
for epoch in range(epochs):
    train_loss = 0.0

    for data in train_loader:
        img, _ = data  # We only need images for VAE

        optimizer.zero_grad()  # Clear gradients

        recon_batch, mu, logvar = model(img.view(-1, input_dim))  # Forward pass

        loss = loss_function(recon_batch, img.view(-1, input_dim), mu, logvar)  # Compute loss
        loss.backward()  # Backward pass

        train_loss += loss.item()
        optimizer.step()  # Update weights

    print(f'Epoch {epoch + 1}, Loss: {train_loss / len(train_loader.dataset):.4f}')

"""## Audi Speech Recognition Models"""

# import os
# import librosa
# import numpy as np
# import tensorflow as tf
# from tensorflow.keras import layers
# from sklearn.model_selection import train_test_split

# # Set the path to the directory containing the audio files
# data_dir = '/content'

# # Initialize empty lists to store the spectrograms and labels
# spectrograms = []
# labels = []

# # Loop over the audio files in the directory
# for filename in os.listdir(data_dir):
#     # Load the audio file
#     audio, sample_rate = librosa.load(os.path.join(data_dir, filename), sr=None)

#     # Compute the spectrogram
#     spectrogram = librosa.feature.melspectrogram(y=audio, sr=sample_rate)

#     # Convert the spectrogram to a 3D tensor with shape (1, time, frequency, channels)
#     spectrogram = np.expand_dims(spectrogram, axis=0)
#     spectrogram = np.expand_dims(spectrogram, axis=-1)

#     # Extract the label from the filename (assuming the filename is in the format 'label_number.wav')
#     label = int(filename.split('_')[0])

#     # Add the spectrogram and label to the lists
#     spectrograms.append(spectrogram)
#     labels.append(label)

# # Convert the lists to numpy arrays
# spectrograms = np.concatenate(spectrograms, axis=0)
# labels = np.array(labels)

# # Split the data into training and validation sets
# X_train, X_val, y_train, y_val = train_test_split(spectrograms, labels, test_size=0.2, random_state=42)

# # Define the model
# input_shape = (None, 128, 1)  # Audio spectrograms of shape (time, frequency, channels)
# num_classes = 10  # Number of output classes (e.g., digits 0-9)

# model = tf.keras.Sequential([
#     layers.Conv2D(32, (3, 3), activation='relu', input_shape=input_shape),
#     layers.MaxPooling2D((2, 2)),
#     layers.Conv2D(64, (3, 3), activation='relu'),
#     layers.MaxPooling2D((2, 2)),
#     layers.Conv2D(128, (3, 3), activation='relu'),
#     layers.MaxPooling2D((2, 2)),
#     layers.Flatten(),
#     layers.Dense(64, activation='relu'),
#     layers.Dense(num_classes, activation='softmax')
# ])

# # Compile the model
# model.compile(optimizer='adam',
#               loss=tf.keras.losses.SparseCategoricalCrossentropy(),
#               metrics=['accuracy'])

# # Train the model
# model.fit(X_train, y_train, batch_size=32, epochs=10, validation_data=(X_val, y_val))

# # Load an audio file for prediction
# filename = '/content/PamKuu_Chp2_12.wav'
# audio, sample_rate = librosa.load(filename, sr=None)
# spectrogram = librosa.feature.melspectrogram(y=audio, sr=sample_rate)
# spectrogram = np.expand_dims(spectrogram, axis=0)
# spectrogram = np.expand_dims(spectrogram, axis=-1)
# #
# # Make a prediction
# prediction = model.predict(spectrogram)
# predicted_class = np.argmax(prediction)

# print(f'Predicted class: {predicted_class}')



"""### Natural Language Processing"""



import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from collections import Counter
import numpy as np

sentences = [
    "I love programming",
    "This is the worst thing I have ever heard",
    "Perfect wonderful, amazing work",
    "Not worth my time",
    "Satisfying videos here",
    "I will never buy this"
]

labels = ["positive","negative","positive","negative","positive","negative"]


tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)
sequences = tokenizer.texts_to_sequences(sentences)
sequences

encoder = LabelEncoder()
labels = encoder.fit_transform(labels)
labels

max_length = 5
padded_sequences = pad_sequences(sequences, maxlen=max_length, padding='post')
padded_sequences

train_texts, test_texts, train_labels, test_labels = train_test_split(padded_sequences, labels, test_size=0.2, random_state=42)

vocab_size = len(tokenizer.word_index) + 1
embedding_dim = 10
hidden_size = 128
output_size = len(set(labels))
num_layers = 1

model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_length),
    SimpleRNN(hidden_size, return_sequences=False),
    Dense(output_size, activation='softmax')
])

loss_fn = tf.keras.losses.SparseCategoricalCrossentropy()
optimizer = tf.keras.optimizers.Adam()

model.compile(loss=loss_fn, optimizer=optimizer, metrics=['accuracy'])

epochs = 5
model.fit(train_texts, train_labels, epochs=epochs, validation_data=(test_texts, test_labels))

model.evaluate(test_texts, test_labels)

predictions = model.predict(test_texts)

predictions

test_texts