dag:
- access_control: null
  auto_register: false
  catchup: false
  concurrency: null
  connection_id: -OAXVyYdLLm5cpkAWuCn
  created_at: 2024-12-04 09:34:12.539286+00:00
  dag_id: obusde
  dagrun_timeout: null
  default_args: null
  default_view: null
  deleted_at: null
  description: testdesc
  doc_md: null
  end_date: null
  fail_stop: false
  full_filepath: null
  http_conn_id: martin_connection
  id: -ODG0GmWwn_q22V9RwSb
  is_paused_upon_creation: false
  jinja_environment_kwargs: null
  max_active_runs: null
  max_active_tasks: null
  on_failure_callback: null
  on_success_callback: null
  orientation: null
  owner_links: null
  params: null
  render_template_as_native_obj: false
  schedule: '2025-01-01'
  schedule_interval: 0 0 * * *
  sla_miss_callback: null
  start_date: null
  tags: null
  template_searchpath: null
  template_undefined: null
  timetable: null
  trigger_url: /v1/instagram/
  trigger_url_expected_key: status
  trigger_url_expected_value: ready
  updated_at: 2024-12-04 09:34:12.539332+00:00
  user_defined_filters: null
  user_defined_macros: null
  workflow_id: -ODG0GUKgvolXLQ7i18h
data_seconds:
- '12'
operators:
- connection_id: -OAXVyYdLLm5cpkAWuCn
  created_at: 2024-12-04 09:34:14.485250+00:00
  dag_id: -ODG0GmWwn_q22V9RwSb
  data:
    body: bar
    title: foo
    userId: 1
  deleted_at: null
  endpoint: /posts
  endpointurl_id: -OB9603E2pAYCnUpdwAj
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: martin_connection
  id: -ODG0HEKLNdhNuY3G85Q
  log_response: false
  method: POST
  response_check: null
  task_id: first_endpoint
  updated_at: 2024-12-04 09:34:14.485314+00:00
  urls: null
  xcom_push: true
