dag:
- access_control: null
  auto_register: false
  catchup: false
  concurrency: null
  connection_id: -OZxDOXms8MnQiVs0gbZ
  created_at: 2025-09-17 13:00:46.066327+00:00
  dag_id: testing
  dagrun_timeout: null
  default_args: null
  default_view: null
  deleted_at: null
  description: testing
  doc_md: null
  end_date: null
  fail_stop: false
  full_filepath: null
  http_conn_id: data_pipeline_connection
  id: -O_MkpsrzDTXVseJ1JaQ
  is_paused_upon_creation: false
  jinja_environment_kwargs: null
  max_active_runs: null
  max_active_tasks: null
  on_failure_callback: null
  on_success_callback: null
  orientation: null
  owner_links: null
  params: null
  render_template_as_native_obj: false
  schedule: '2025-01-01'
  schedule_interval: 0 0 * * *
  sla_miss_callback: null
  start_date: null
  tags: null
  template_searchpath: null
  template_undefined: null
  timetable: null
  trigger_url: null
  trigger_url_expected_key: null
  trigger_url_expected_value: null
  updated_at: 2025-09-17 13:00:46.066367+00:00
  user_defined_filters: null
  user_defined_macros: null
  workflow_id: -O_MkpeSVKX6BwXe_9DS
data_seconds:
- '10'
operators:
- connection_id: -OZxDOXms8MnQiVs0gbZ
  created_at: 2025-09-17 13:00:47.290773+00:00
  dag_id: -O_MkpsrzDTXVseJ1JaQ
  data: null
  deleted_at: null
  endpoint: /facebook/pages/100747912772086/
  endpointurl_id: -O_GZQ5vSXhV9oWpfQ-A
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: data_pipeline_connection
  id: -O_MkqB3AM6IVsHhkJV7
  log_response: false
  method: GET
  response_check: null
  task_id: generating
  updated_at: 2025-09-17 13:00:47.290845+00:00
  urls: null
  xcom_push: true
