# Generated by Django 5.1.3 on 2025-09-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('listen', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='chatsession',
            name='stop',
            field=models.BooleanField(default=False),
        ),
    ]
