# Generated by Django 5.1.3 on 2025-10-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_group_chatsession_stop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_off', models.BooleanField(default=False)),
            ],
        ),
    ]
