from django.urls import path
from . import views

urlpatterns = [
    path('gmail/accounts/', views.GmailAccountsView.as_view(), name='gmail_accounts'),
    path('gmail/accounts/<str:account_id>/', views.GmailAccountView.as_view(), name='gmail_account'),
    path('gmail/accounts/<str:account_id>/connect/', views.GmailAccountConnectView.as_view(), name='gmail_account_connect'),
    path('gmail/accounts/<str:account_id>/disconnect/', views.GmailAccountDisconnectView.as_view(), name='gmail_account_disconnect'),
    path('gmail/accounts/<str:account_id>/emails/', views.GmailEmailsView.as_view(), name='gmail_emails'),
    path('gmail/accounts/<str:account_id>/emails/<str:email_id>/', views.GmailEmailView.as_view(), name='gmail_email'),
    path('gmail/accounts/<str:account_id>/emails/<str:email_id>/reply/', views.GmailEmailReplyView.as_view(), name='gmail_email_reply'),
    path('gmail/accounts/<str:account_id>/emails/<str:email_id>/forward/', views.GmailEmailForwardView.as_view(), name='gmail_email_forward'),
    path('gmail/accounts/<str:account_id>/campaigns/', views.GmailCampaignsView.as_view(), name='gmail_campaigns'),
    path('gmail/accounts/<str:account_id>/campaigns/<str:campaign_id>/', views.GmailCampaignView.as_view(), name='gmail_campaign'),
    path('gmail/accounts/<str:account_id>/campaigns/<str:campaign_id>/control/', views.GmailCampaignControlView.as_view(), name='gmail_campaign_control'),
    path('gmail/accounts/<str:account_id>/campaigns/<str:campaign_id>/recipients/', views.GmailCampaignRecipientsView.as_view(), name='gmail_campaign_recipients'),
    path('gmail/accounts/<str:account_id>/campaigns/<str:campaign_id>/analytics/', views.GmailCampaignAnalyticsView.as_view(), name='gmail_campaign_analytics'),
    path('gmail/accounts/<str:account_id>/sequences/', views.GmailSequencesView.as_view(), name='gmail_sequences'),
    path('gmail/accounts/<str:account_id>/sequences/<str:sequence_id>/', views.GmailSequenceView.as_view(), name='gmail_sequence'),
    path('gmail/accounts/<str:account_id>/sequences/<str:sequence_id>/enroll/', views.GmailSequenceEnrollView.as_view(), name='gmail_sequence_enroll'),
    path('gmail/accounts/<str:account_id>/templates/', views.GmailTemplatesView.as_view(), name='gmail_templates'),
    path('gmail/accounts/<str:account_id>/templates/<str:template_id>/', views.GmailTemplateView.as_view(), name='gmail_template'),
    path('gmail/accounts/<str:account_id>/templates/<str:template_id>/preview/', views.GmailTemplatePreviewView.as_view(), name='gmail_template_preview'),
    path('gmail/accounts/<str:account_id>/contact-lists/', views.GmailContactListsView.as_view(), name='gmail_contact_lists'),
    path('gmail/accounts/<str:account_id>/contact-lists/<str:list_id>/', views.GmailContactListView.as_view(), name='gmail_contact_list'),
    path('gmail/accounts/<str:account_id>/contact-lists/<str:list_id>/contacts/', views.GmailContactListContactsView.as_view(), name='gmail_contact_list_contacts'),
    path('gmail/accounts/<str:account_id>/contacts/', views.GmailContactsView.as_view(), name='gmail_contacts'),
    path('gmail/accounts/<str:account_id>/contacts/<str:contact_id>/', views.GmailContactView.as_view(), name='gmail_contact'),
    path('gmail/accounts/<str:account_id>/tracking/', views.GmailTrackingView.as_view(), name='gmail_tracking'),
    path('gmail/tracking/pixel/<str:tracking_id>/', views.GmailTrackingPixelView.as_view(), name='gmail_tracking_pixel'),
    path('gmail/accounts/<str:account_id>/analytics/', views.GmailAnalyticsView.as_view(), name='gmail_analytics'),
    path('gmail/accounts/<str:account_id>/deliverability/', views.GmailDeliverabilityView.as_view(), name='gmail_deliverability'),
    path('gmail/accounts/<str:account_id>/domain-reputation/', views.GmailDomainReputationView.as_view(), name='gmail_domain_reputation'),
    path('gmail/accounts/<str:account_id>/spam-test/', views.GmailSpamTestView.as_view(), name='gmail_spam_test'),
    path('gmail/accounts/<str:account_id>/warmup/', views.GmailWarmupView.as_view(), name='gmail_warmup'),
    path('gmail/accounts/<str:account_id>/attachments/', views.GmailAttachmentsView.as_view(), name='gmail_attachments'),
    path('gmail/accounts/<str:account_id>/attachments/<str:attachment_id>/', views.GmailAttachmentsView.as_view(), name='gmail_attachment'),
    path('gmail/accounts/<str:account_id>/folders/', views.GmailFoldersView.as_view(), name='gmail_folders'),
    path('gmail/accounts/<str:account_id>/folders/<str:folder_id>/', views.GmailFolderView.as_view(), name='gmail_folder'),
    path('gmail/accounts/<str:account_id>/bulk-operations/', views.GmailBulkOperationsView.as_view(), name='gmail_bulk_operations'),
    path('gmail/accounts/<str:account_id>/webhooks/', views.GmailWebhooksView.as_view(), name='gmail_webhooks'),
    path('gmail/accounts/<str:account_id>/webhooks/<str:webhook_id>/', views.GmailWebhookView.as_view(), name='gmail_webhook'),
    path('gmail/accounts/<str:account_id>/search/', views.GmailSearchView.as_view(), name='gmail_search'),
    path('gmail/accounts/<str:account_id>/unsubscribed/', views.GmailUnsubscribeView.as_view(), name='gmail_unsubscribed'),
    path('gmail/accounts/<str:account_id>/validate/', views.GmailValidationView.as_view(), name='gmail_validate'),
    path('gmail/accounts/<str:account_id>/blacklist/', views.GmailBlacklistView.as_view(), name='gmail_blacklist'),
]