# Generated by Django 5.1.3 on 2025-09-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='subscription',
            field=models.CharField(blank=True, choices=[('2000', '2,000 KES'), ('5000', '5,000 KES'), ('10000', '10,000 KES'), ('20000', '20,000 KES'), ('50000', '50,000 KES')], max_length=100, null=True),
        ),
    ]
