# Generated by Django 5.1.3 on 2025-09-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0003_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='instagram_business_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='page_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
