# Generated by Django 5.1.3 on 2025-10-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0004_client_instagram_business_account_id_client_page_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='whatsapp_channel_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
