# Generated by Django 5.1.3 on 2025-10-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0005_client_whatsapp_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='whatsapp_channel_token',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
