# Generated by Django 5.1.3 on 2025-10-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0006_client_whatsapp_channel_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='subscription',
            field=models.CharField(blank=True, choices=[('0', 'Free'), ('2000', '2,000 KES'), ('5000', '5,000 KES'), ('10000', '10,000 KES'), ('20000', '20,000 KES'), ('50000', '50,000 KES')], max_length=100, null=True),
        ),
    ]
