# Generated by Django 5.1.3 on 2025-11-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0007_alter_client_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='subscription',
            field=models.CharField(blank=True, choices=[('0', 'Free'), ('500', '500 KES'), ('1000', '1,000 KES'), ('2000', '2,000 KES'), ('20000', '20,000 KES'), ('50000', '50,000 KES')], max_length=100, null=True),
        ),
    ]
