name: Deploy to staging

on:
  push:
    branches: [ actions-test ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: lunyamwimages/scrapper-dev:latest

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker compose build --no-cache --force-rm 
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
   
    - name: Login To Docker Hub
      uses: docker/login-action@v3 # mr-smithers-excellent/docker-build-push@v4 # use existing coker action
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}"
        push: true
        tags: lunyamwimages/scrapper-dev:latest

    - name: Set up ssh agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.STAGING_DEPLOY_SSH_PRIVATE_KEY }}

    - name: Add server to known_hosts
      run: |
        ssh-keyscan -H 84.247.184.136 >> ~/.ssh/known_hosts

    - name: Test SSH connection
      run: |
        ssh -v ubuntu@84.247.184.136 'echo "I AM IN THE SERVER"'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.STAGING_DEPLOY_SSH_PRIVATE_KEY }}
  
    - name: Pull staging image and builde docker on staging server
      run: |
       ssh ubuntu@84.247.184.136 '
          cd /home/ubuntu/booksy-boostedchat-deployment/boostedchat-site && \
          docker pull lunyamwimages/scrapper-dev:latest && \
          if [ "$(docker ps -a -q -f name=boostedchat-site-web-1)" ]; then \
            docker stop boostedchat-site-web-1 && docker rm boostedchat-site-web-1 && \
            unset DOCKER_HOST && docker compose --env-file .env -f docker-compose.airflow.yaml up --build -d web; \
          else \
            echo "No such container: boostedchat-site-web-1, starting web service" && docker compose -f docker-compose.airflow.yaml --env-file .env up -d web; \
          fi  
        '

      env:
        SSH_PRIVATE_KEY: ${{ secrets.STAGING_DEPLOY_SSH_PRIVATE_KEY }} 